export enum RoutingPreference {
  ROUTING_PREFERENCE_UNSPECIFIED = "ROUTING_PREFERENCE_UNSPECIFIED",
  TRAFFIC_UNAWARE = "TRAFFIC_UNAWARE",
  TRAFFIC_AWARE = "TRAFFIC_AWARE",
  TRAFFIC_AWARE_OPTIMAL = "TRAFFIC_AWARE_OPTIMAL"
}
